---
title: "SDS 192 Assignment"
subtitle: "SDS 192"
author: 
- name: Author One
  affiliation: Smith College
- name: Author Two
  affiliation: Smith College
date: "`r format(Sys.Date(), '%B %e, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    fig_width: 7
    fig_height: 6
    fig_caption: true
    theme: lumen
    df_print: paged
    code_folding: show
---

```{r}
#Load the ggplot library here.
library(ggplot2)
```

```{r}
pioneer_valley_2013 <- read.csv("https://raw.githubusercontent.com/SDS-192-Intro/sds-192-labs/main/Day7-GrammarGraphics/datasets/pioneer_valley_census_2013.csv", skip = 2)
pioneer_valley_2013_dictionary <- read.csv("https://raw.githubusercontent.com/SDS-192-Intro/sds-192-labs/main/Day7-GrammarGraphics/datasets/pioneer_valley_census_2013_dictionary.csv")
```

1. Check column names and values.

```{r}
#Check the column names for pioneer_valley_2013. View what column names refer to via pioneer_valley_2013_dictionary
names(pioneer_valley_2013)
```
